"""
Aplica traducciones al castellano sobre paintings.json.
Las traducciones están embebidas en el diccionario TRADUCCIONES.
Títulos en francés, chino, japonés u otros idiomas se dejan tal cual.
"""

import json
from pathlib import Path

PATH = Path(__file__).parent.parent / "app" / "data" / "paintings.json"

TRADUCCIONES: dict[str, str] = {
    # A
    "A Boy Blowing on a Firebrand": "Un niño soplando un tizón",
    "A Holiday": "Un día festivo",
    "A Lady Reading (Saint Mary Magdalene)": "Una dama leyendo (Santa María Magdalena)",
    "A Pair of Carp": "Una pareja de carpas",
    "A Vanitas Still Life with a Flag, Candlestick, Musical Instruments, Books, Writing Paraphernalia, Globes, and Hourglass": "Vanitas con bandera, candelabro, instrumentos musicales, libros, utensilios de escritura, globos y reloj de arena",
    "A Witches' Sabbath": "El aquelarre",
    "Acrobats at the Cirque Fernando (Francisca and Angelina Wartenberg)": "Acróbatas en el Cirque Fernando (Francisca y Angelina Wartenberg)",
    "After the Bullfight": "Después de la corrida",
    "Afterglow": "Resplandor del crepúsculo",
    "Allegory of Charity": "Alegoría de la Caridad",
    "Allegory of Peace and War": "Alegoría de la Paz y la Guerra",
    "An Italian Comedy in Verona": "Una comedia italiana en Verona",
    "Apples": "Manzanas",
    "Apples and Grapes": "Manzanas y uvas",
    "Arab Horseman Attacked by a Lion": "Jinete árabe atacado por un león",
    "Armida Abandoned by Rinaldo": "Armida abandonada por Rinaldo",
    "Armida Encounters the Sleeping Rinaldo": "Armida encuentra a Rinaldo dormido",
    "Arrangement in Flesh Color and Brown: Portrait of Arthur Jerome Eddy": "Composición en color carne y marrón: Retrato de Arthur Jerome Eddy",
    "Arrival of the Normandy Train, Gare Saint-Lazare": "Llegada del tren de Normandía, Gare Saint-Lazare",
    "At the Circus: The Bareback Rider (Au Cirque: Écuyère)": "En el circo: la amazona",
    "Autumn Maples with Poem Slips": "Arces otoñales con tiras de poemas",
    "Autumn Woods": "Bosque otoñal",
    "Auvers, Panoramic View": "Auvers, vista panorámica",
    # B
    "Bamboo-Covered Stream in Spring Rain": "Arroyo entre bambúes en la lluvia primaveral",
    "Beggar with Oysters (Philosopher)": "Mendigo con ostras (Filósofo)",
    "Beggar with a Duffle Coat (Philosopher)": "Mendigo con abrigo (Filósofo)",
    "Bird's Nest and Ferns": "Nido de pájaro y helechos",
    "Birth of Bacchus": "Nacimiento de Baco",
    "Boats at Rest": "Barcas en reposo",
    "Boats on the Beach at Étretat": "Barcas en la playa de Étretat",
    "Boy of Hallett Family with Dog": "Niño de la familia Hallett con perro",
    "Boy on a Ram": "Niño sobre un carnero",
    "Boy with Pitcher (La Régalade)": "Niño con jarra",
    "Branch of the Seine near Giverny (Mist)": "Brazo del Sena cerca de Giverny (Niebla)",
    "Bullfight": "Corrida de toros",
    # C
    "Cabin in the Cotton": "Cabaña entre el algodón",
    "Calf's Head and Ox Tongue": "Cabeza de ternera y lengua de buey",
    "Catskill Mountains": "Montañas Catskill",
    "Ceremony of the Fastest Horse": "Ceremonia del caballo más veloz",
    "Charing Cross Bridge, London": "Puente de Charing Cross, Londres",
    "Christ Carrying the Cross": "Cristo portando la Cruz",
    "Christ Washing the Feet of His Disciples": "Cristo lavando los pies de sus discípulos",
    "Christ on the Living Cross": "Cristo en la Cruz viviente",
    "Chrysanthemums": "Crisantemos",
    "Cliff Walk at Pourville": "Paseo por los acantilados de Pourville",
    "Coast Scene, Bathers": "Escena costera, bañistas",
    "Colonnade and Gardens of the Medici Palace": "Columnata y jardines del Palacio Médici",
    "Crucifixion": "Crucifixión",
    # D
    "Daniel Saving Susanna, the Judgment of Daniel, and the Execution of the Elders": "Daniel salvando a Susana, el juicio de Daniel y la ejecución de los ancianos",
    "Dedication (Odes and Sonnets)": "Dedicatoria (Odas y Sonetos)",
    "Deposition": "El Descendimiento",
    "Distant View of Niagara Falls": "Vista lejana de las cataratas del Niágara",
    "Don Quixote and the Windmills": "Don Quijote y los molinos de viento",
    "Drinking at Night": "Bebiendo de noche",
    # E
    "Early Morning, Tarpon Springs": "Primera mañana en Tarpon Springs",
    "Emperor Heraclius Denied Entry into Jerusalem": "El emperador Heraclio rechazado en Jerusalén",
    "Equestrienne (At the Cirque Fernando)": "Amazona (En el Cirque Fernando)",
    # F
    "Fish": "Pez",
    "Fish (Still Life)": "Pez (Naturaleza muerta)",
    "Fishing Boats with Hucksters Bargaining for Fish": "Barcas de pesca con buhoneros regateando el pescado",
    "Flight of Geese": "Vuelo de gansos",
    "Flower Arrangements": "Composiciones florales",
    "Flowers and Fruit in a Chinese Bowl": "Flores y fruta en un cuenco chino",
    "Flowers of the Four Seasons": "Flores de las cuatro estaciones",
    "For Sunday's Dinner": "Para la cena del domingo",
    "Fountain and Pergola in Italy": "Fuente y pérgola en Italia",
    "Fruit Piece": "Naturaleza muerta con frutas",
    "Fruits of the Midi": "Frutos del Mediodía",
    # G
    "Ghost Dance (The Vision of Life)": "Danza de los Espíritus (La visión de la vida)",
    "Girl with Cherries": "Niña con cerezas",
    "Grapes, Lemons, Pears, and Apples": "Uvas, limones, peras y manzanas",
    "Grey and Silver: Old Battersea Reach": "Gris y plata: antiguo tramo de Battersea",
    # H
    "Harvest, Montclair, New Jersey": "Cosecha, Montclair, Nueva Jersey",
    "Haymaking at Éragny": "Henificación en Éragny",
    "Head of a Philosopher": "Cabeza de filósofo",
    "Hercules and the Lernaean Hydra": "Hércules y la Hidra de Lerna",
    "Houses of Parliament, London": "Parlamento de Londres",
    "Houses on the Fox River, Illinois": "Casas junto al río Fox, Illinois",
    "Ice-Bound Falls": "Cascadas heladas",
    "Icebound": "Atrapado por el hielo",
    "Improvisation No. 30 (Cannons)": "Improvisación n.º 30 (Cañones)",
    "In the Auvergne": "En la Auvernia",
    "In the Café": "En el café",
    "Inside the Colosseum": "Interior del Coliseo",
    "Interior of St. Mark's, Venice": "Interior de San Marcos, Venecia",
    "Irises": "Lirios",
    "Italian Landscape": "Paisaje italiano",
    # J
    "Jean Renoir Sewing": "Jean Renoir cosiendo",
    "Jesus Mocked by the Soldiers": "Jesús burlado por los soldados",
    "Judith with the Head of Holofernes": "Judit con la cabeza de Holofernes",
    # K
    "Keats' Last Sonnet": "El último soneto de Keats",
    # L
    "Lady Reading the Letters of Heloise and Abelard": "Dama leyendo las cartas de Eloísa y Abelardo",
    "Lady Sarah Bunbury Sacrificing to the Graces": "Lady Sarah Bunbury sacrificando a las Gracias",
    "Landscape": "Paisaje",
    "Landscape (The Lock)": "Paisaje (La esclusa)",
    "Landscape Painting": "Pintura de paisaje",
    "Landscape near Chiusi, Tuscany": "Paisaje cerca de Chiusi, Toscana",
    "Landscape with Saint John on Patmos": "Paisaje con San Juan en Patmos",
    "Landscape with the Ruins of the Castle of Egmond": "Paisaje con las ruinas del castillo de Egmond",
    "Landscape, Sunset": "Paisaje al atardecer",
    "Lights of Other Days": "Luces de otros tiempos",
    "Lion Hunt": "La caza del león",
    "Lozenge Composition with Yellow, Black, Blue, Red, and Gray": "Composición en rombo con amarillo, negro, azul, rojo y gris",
    "Lucie Berard (Child in White)": "Lucie Berard (Niña de blanco)",
    "Lunch at the Restaurant Fournaise (The Rowers' Lunch)": "Almuerzo en el restaurante Fournaise (El almuerzo de los remeros)",
    # M
    "Madame Cezanne in a Yellow Chair": "Madame Cézanne en una silla amarilla",
    "Madame de Pastoret and Her Son": "Madame de Pastoret y su hijo",
    "Madonna and Child with Saints Elizabeth and John the Baptist": "Virgen con el Niño, Santa Isabel y San Juan Bautista",
    "Man in Black": "Hombre de negro",
    "Margaret of Austria, Queen of Spain": "Margarita de Austria, reina de España",
    "Moonrise": "Salida de la luna",
    "Morning": "Mañana",
    "Mountain Brook": "Arroyo de montaña",
    # N
    "Near the Lake": "Junto al lago",
    "New England Headlands": "Acantilados de Nueva Inglaterra",
    "New England Scenery": "Paisaje de Nueva Inglaterra",
    "Nicolas Rubens, the Artist's Son": "Nicolás Rubens, hijo del artista",
    "Nocturne: Blue and Gold—Southampton Water": "Nocturno: azul y oro — aguas de Southampton",
    "Nothing But Cheerful Looks Followed the Bat": "Solo miradas alegres siguieron al murciélago",
    # O
    "Odalisque": "Odalisca",
    "Old Man with a Gold Chain": "Anciano con cadena de oro",
    "Old Tower at Avignon": "Torre antigua en Aviñón",
    "On a Balcony": "En un balcón",
    "On the Bank of the Seine, Bennecourt": "A orillas del Sena, Bennecourt",
    "Orchids": "Orquídeas",
    # P
    "Panels from the High Altar of the Charterhouse of Saint-Honoré, Thuison-les-Abbeville: Pentecost": "Paneles del altar mayor de la Cartuja de Saint-Honoré: Pentecostés",
    "Pardon in Brittany": "Perdón en Bretaña",
    "Paris Street; Rainy Day": "Calle de París; Día lluvioso",
    "Pastoral Scene": "Escena pastoral",
    "Peasant Family at a Well": "Familia campesina junto a un pozo",
    "Peasants Bringing Home a Calf Born in the Fields": "Campesinos llevando a casa un ternero nacido en los campos",
    "Peonies, Magnolia, and Dandelions": "Peonías, magnolia y dientes de león",
    "Pergola with Oranges": "Pérgola con naranjos",
    "Pillars of the Country": "Pilares del país",
    "Polynesian Woman with Children": "Mujer polinesia con niños",
    "Pond in the Woods": "Estanque en el bosque",
    "Poppy Field (Giverny)": "Campo de amapolas (Giverny)",
    "Portrait of Cardinal Zelada": "Retrato del cardenal Zelada",
    "Portrait of Constance Pipelet": "Retrato de Constance Pipelet",
    "Portrait of Dr. William McNeill Whistler": "Retrato del Dr. William McNeill Whistler",
    "Portrait of Emmanuel Rio": "Retrato de Emmanuel Rio",
    "Portrait of Louise de Halluin, dame de Cipierre": "Retrato de Louise de Halluin, dama de Cipierre",
    "Portrait of a Gentleman": "Retrato de un caballero",
    "Portrait of a Girl with a Dog": "Retrato de una niña con perro",
    "Portrait of a Man": "Retrato de un hombre",
    "Portrait of a Man in Costume": "Retrato de un hombre disfrazado",
    "Portrait of a Man with a Pink": "Retrato de un hombre con un clavel",
    "Portrait of a Musician": "Retrato de un músico",
    "Portrait of a Woman": "Retrato de una mujer",
    "Portrait of a Woman with a Black Fichu": "Retrato de una mujer con fichu negro",
    "Portrait of a Young Woman": "Retrato de una mujer joven",
    "Portrait of an Artist": "Retrato de un artista",
    "Portrait of the Artist's Father, Ismael Mengs": "Retrato del padre del artista, Ismael Mengs",
    "Portrait of the Katchef Dahouth, Christian Mameluke": "Retrato del Katchef Dahouth, mameluco cristiano",
    "Portrait of the Princess di Ottaiano and her son Carlo": "Retrato de la princesa di Ottaiano y su hijo Carlo",
    "Prunus and Bamboo": "Ciruelo y bambú",
    # R
    "Rabbit Warren at Pontoise, Snow": "Madriguera de conejos en Pontoise, nieve",
    "Ravine Near Biskra": "Barranco cerca de Biskra",
    "Rebirth of the Nun Anyo": "Renacimiento de la monja Anyo",
    "Recluse Dwellings in the Autumn Mountains": "Moradas de ermitaños en las montañas otoñales",
    "Resting": "Descansando",
    "Retable and Frontal of the Life of Christ and the Virgin": "Retablo y frontal de la vida de Cristo y la Virgen",
    "Retable of Saints Athanasius, Blaise, and Agatha": "Retablo de los santos Atanasio, Blas y Águeda",
    "Rinaldo and Armida in Her Garden": "Rinaldo y Armida en su jardín",
    "Rinaldo and the Magus of Ascalon": "Rinaldo y el mago de Ascalón",
    "River and Mountain Landscape": "Paisaje de río y montaña",
    "Rocks at Port-Goulphar, Belle-Île": "Rocas en Port-Goulphar, Belle-Île",
    "Ruler Entertained by Dancers in a Paradise Garden": "Soberano entretenido por bailarines en un jardín paradisíaco",
    # S
    "Saint Andrew": "San Andrés",
    "Saint Francis Kneeling in Meditation": "San Francisco arrodillado en meditación",
    "Saint George and the Dragon": "San Jorge y el dragón",
    "Saint Jerome in Penitence": "San Jerónimo en penitencia",
    "Saint Jerome in the Wilderness": "San Jerónimo en el desierto",
    "Saint John the Baptist": "San Juan Bautista",
    "Saint John the Baptist Preaching in the Desert": "San Juan Bautista predicando en el desierto",
    "Saint John the Evangelist and Donor": "San Juan Evangelista y donante",
    "Saint Sebastian": "San Sebastián",
    "Salome with the Head of Saint John the Baptist": "Salomé con la cabeza de San Juan Bautista",
    "Sawmill, Outskirts of Paris": "Aserradero, afueras de París",
    "Scenes from the Life of Saint John the Baptist": "Escenas de la vida de San Juan Bautista",
    "Seated Bather": "Bañista sentada",
    "Self-Portrait": "Autorretrato",
    "Sketch for The Revolt of Cairo": "Boceto para La revuelta de El Cairo",
    "Sketch for a Ceiling Fresco": "Boceto para un fresco de techo",
    "Slave Market": "Mercado de esclavos",
    "Snow Field, Morning, Roxbury": "Campo nevado, mañana, Roxbury",
    "Snow at Louveciennes": "Nieve en Louveciennes",
    "Song of a Fisherman": "Canción de un pescador",
    "Spring in France": "Primavera en Francia",
    "Springtime": "Primavera",
    "Squirrel and Grapes": "Ardilla y uvas",
    "St. Joseph and Christ Child": "San José y el Niño Jesús",
    "Stack of Wheat": "Paca de trigo",
    "Stack of Wheat (Snow Effect, Overcast Day)": "Paca de trigo (efecto de nieve, día nublado)",
    "Stack of Wheat (Thaw, Sunset)": "Paca de trigo (deshielo, atardecer)",
    "Stacks of Wheat (End of Day, Autumn)": "Pacas de trigo (final del día, otoño)",
    "Stacks of Wheat (End of Summer)": "Pacas de trigo (fin del verano)",
    "Stacks of Wheat (Sunset, Snow Effect)": "Pacas de trigo (atardecer, efecto de nieve)",
    "Staircase in the Park of Villa Chigi di Ariccia": "Escalinata en el parque de la Villa Chigi di Ariccia",
    "Standing Bather, Seen from the Back": "Bañista de pie, vista de espaldas",
    "Still Life with Geranium": "Naturaleza muerta con geranio",
    "Still Life with Grapes and Flowers": "Naturaleza muerta con uvas y flores",
    "Still Life with Monkey, Fruits, and Flowers": "Naturaleza muerta con mono, frutas y flores",
    "Still Life: Wood Tankard and Metal Pitcher": "Naturaleza muerta: jarra de madera y pichel de metal",
    "Still Life—Strawberries, Nuts, &c.": "Naturaleza muerta — fresas, nueces, etc.",
    "Storm in Umbria": "Tormenta en Umbría",
    "Street in Moret": "Calle en Moret",
    "Study for \"Arrangement in Grey and Black, No. 2: Portrait of Thomas Carlyle\"": "Estudio para Composición en gris y negro, n.º 2: Retrato de Thomas Carlyle",
    "Study of Two Bedouins": "Estudio de dos beduinos",
    "Study of a Girl's Head and Shoulders": "Estudio de cabeza y hombros de una niña",
    "Sunlit Valley": "Valle iluminado por el sol",
    "Susanna and the Elders in the Garden, and the Trial of Susanna before the Elders": "Susana y los ancianos en el jardín, y el juicio de Susana ante los ancianos",
    # T
    "The Actor Maximilian Korn in a Landscape": "El actor Maximilian Korn en un paisaje",
    "The Adoration of the Magi": "La Adoración de los Magos",
    "The Adventures of Ulysses": "Las aventuras de Ulises",
    "The Annunciation": "La Anunciación",
    "The Apple Market": "El mercado de manzanas",
    "The Artist in His Studio": "El artista en su estudio",
    "The Artist's House at Argenteuil": "La casa del artista en Argenteuil",
    "The Assumption of the Virgin": "La Asunción de la Virgen",
    "The August Moon": "La luna de agosto",
    "The Banks of the Marne in Winter": "Las orillas del Marne en invierno",
    "The Basket of Apples": "La cesta de manzanas",
    "The Bathers": "Los bañistas",
    "The Battle of Pharsalus and the Death of Pompey": "La batalla de Farsalia y la muerte de Pompeyo",
    "The Bay of Marseille, Seen from L'Estaque": "La bahía de Marsella, vista desde L'Estaque",
    "The Beach at Sainte-Adresse": "La playa de Sainte-Adresse",
    "The Beautiful Greek Woman": "La bella griega",
    "The Bedroom": "El dormitorio",
    "The Beggar Boy (The Young Pilgrim)": "El niño mendigo (el joven peregrino)",
    "The Beheading of Saint John the Baptist": "La decapitación de San Juan Bautista",
    "The Captive Slave (Ira Aldridge)": "El esclavo cautivo (Ira Aldridge)",
    "The Child's Bath": "El baño del niño",
    "The Combat of the Giaour and Hassan": "El combate del Giaour y Hassan",
    "The Continence of Scipio": "La continencia de Escipión",
    "The Conversation": "La conversación",
    "The Crucifixion": "La Crucifixión",
    "The Crystal Palace": "El Palacio de Cristal",
    "The Customs House at Varengeville": "La aduana de Varengeville",
    "The Denial of Saint Peter": "La negación de San Pedro",
    "The Departure of the Boats, Étretat": "La partida de los barcos, Étretat",
    "The Dream of Saint Jerome": "El sueño de San Jerónimo",
    "The Dreamer (La Rêveuse)": "La soñadora",
    "The Earl of Coventry's Horse": "El caballo del conde de Coventry",
    "The Entombment": "El Descendimiento",
    "The Eruption of Vesuvius": "La erupción del Vesubio",
    "The Fairies": "Las hadas",
    "The Family Concert": "El concierto familiar",
    "The Fates Gathering in the Stars": "Las Parcas reunidas entre las estrellas",
    "The Feast in the House of Simon": "El banquete en casa de Simón",
    "The Fire Eater Raised His Arms to the Thunder Bird": "El tragafuegos alzó los brazos hacia el pájaro del trueno",
    "The Five Virtues": "Las cinco virtudes",
    "The Fountain at Grottaferrata": "La fuente de Grottaferrata",
    "The Fountain, Villa Torlonia, Frascati, Italy": "La fuente, Villa Torlonia, Frascati, Italia",
    "The Fountains": "Las fuentes",
    "The Garden of Palazzo Contarini dal Zaffo": "El jardín del Palazzo Contarini dal Zaffo",
    "The Girl by the Window": "La niña junto a la ventana",
    "The Grand Canal, Venice": "El Gran Canal, Venecia",
    "The Grey Bodice": "El corpino gris",
    "The Herring Net": "La red de arenques",
    "The Holy Family with Saints Elizabeth and John the Baptist": "La Sagrada Familia con Santa Isabel y San Juan Bautista",
    "The Imperial Palace on the Palatine, Rome": "El Palacio Imperial en el Palatino, Roma",
    "The Interior of the Palm House on the Pfaueninsel Near Potsdam": "El interior del invernadero de palmeras de la isla Pfauen cerca de Potsdam",
    "The Irish Question": "La cuestión irlandesa",
    "The Keeper of the Flock": "El guardián del rebaño",
    "The Landing Place": "El embarcadero",
    "The Last of New England—The Beginning of New Mexico": "El último rincón de Nueva Inglaterra — El comienzo de Nuevo México",
    "The Laundress": "La lavandera",
    "The Lion Hunt": "La caza del león",
    "The Lonely Farm, Nantucket": "La granja solitaria, Nantucket",
    "The Madonna with the Seven Founders of the Servite Order": "La Virgen con los siete fundadores de la Orden de los Servitas",
    "The Marsh": "El pantano",
    "The Meeting of Gautier, Count of Antwerp, and his Daughter, Violante": "El encuentro de Gautier, conde de Amberes, y su hija Violante",
    "The Millinery Shop": "La sombrerería",
    "The Moon at Night": "La luna de noche",
    "The Movings": "La mudanza",
    "The Music Lesson": "La lección de música",
    "The Nativity": "La Natividad",
    "The Obelisk": "El obelisco",
    "The Old Temple": "El templo antiguo",
    "The Petite Creuse River": "El río Petite Creuse",
    "The Place du Havre, Paris": "La Place du Havre, París",
    "The Plate of Apples": "El plato de manzanas",
    "The Poet's Garden": "El jardín del poeta",
    "The Races at Longchamp": "Las carreras en Longchamp",
    "The Rock of Hautepierre": "La roca de Hautepierre",
    "The Sand Pits, Hampstead Heath": "Los arenales de Hampstead Heath",
    "The Scullion": "El fregaplatos",
    "The Shadow of Death": "La sombra de la muerte",
    "The Song of the Lark": "El canto de la alondra",
    "The Squirrel": "La ardilla",
    "The Storm": "La tormenta",
    "The Valley of Les Puits-Noir": "El valle de Les Puits-Noir",
    "The Vase of Tulips": "El jarrón de tulipanes",
    "The Wedding at Cana": "Las bodas de Caná",
    "The White Bridge": "El puente blanco",
    "The White Tablecloth": "El mantel blanco",
    "The Young Emperor Akbar Arrests the Insolent Shah Abu'l-Maali, Page from a Manuscript of the Akbarnama": "El joven emperador Akbar arresta al insolente Shah Abu'l-Maali, página de un manuscrito del Akbarnama",
    "Theodosius Repulsed from the Church by Saint Ambrose": "Teodosio rechazado de la iglesia por San Ambrosio",
    "This Little Pig Went to Market": "Este cerdito fue al mercado",
    "Thistles": "Cardos",
    "Threatening": "Amenazante",
    "Time Unveiling Truth": "El tiempo descubriendo la verdad",
    "Travellers Arriving at an Inn": "Viajeros llegando a una posada",
    "Trompe-l'Oeil Still Life with a Flower Garland and a Curtain": "Trampantojo con guirnalda de flores y cortina",
    "Two Cows and a Young Bull beside a Fence in a Meadow": "Dos vacas y un toro joven junto a una valla en un prado",
    "Two Sisters (On the Terrace)": "Dos hermanas (En la terraza)",
    # V
    "Valley of Aosta: Snowstorm, Avalanche, and Thunderstorm": "Valle de Aosta: ventisca, avalancha y tormenta",
    "Venetian Glass Workers": "Sopladores de vidrio venecianos",
    "Venus, Cupid and Ceres": "Venus, Cupido y Ceres",
    "View of Cotopaxi": "Vista del Cotopaxi",
    "View of Genoa": "Vista de Génova",
    "View of Pirna with the Fortress of Sonnenstein": "Vista de Pirna con la fortaleza de Sonnenstein",
    "View of Saleve, near Geneva": "Vista del Salève, cerca de Ginebra",
    "View on the Grounds of a Villa near Florence": "Vista de los jardines de una villa cerca de Florencia",
    "View on the River Roseau, Dominica": "Vista del río Roseau, Dominica",
    "Violet and Silver—The Deep Sea": "Violeta y plata — El mar profundo",
    "Virgil Reading the \"Aeneid\" to Augustus, Octavia, and Livia": "Virgilio leyendo la Eneida a Augusto, Octavia y Livia",
    "Virgin and Child": "Virgen con el Niño",
    "Virgin and Child with Saints Dominic and Hyacinth": "Virgen con el Niño, Santo Domingo e Hiácinto",
    "Virgin and Child with Two Angels": "Virgen con el Niño y dos ángeles",
    "Virgin and Child with the Young Saint John the Baptist": "Virgen con el Niño y el joven San Juan Bautista",
    # W
    "Washing the Elephant": "Bañando al elefante",
    "Water Carriers on the Nile": "Aguadoras en el Nilo",
    "Water Lilies": "Nenúfares",
    "Water Lily Pond": "Estanque de nenúfares",
    "Watering Place at Marly": "Abrevadero en Marly",
    "Waterloo Bridge, Gray Weather": "Puente de Waterloo, tiempo gris",
    "Waterloo Bridge, Sunlight Effect": "Puente de Waterloo, efecto de luz solar",
    "Wind-Swept Sands": "Arenas barridas por el viento",
    "Woman Bathing Her Feet in a Brook": "Mujer bañando sus pies en un arroyo",
    "Woman Mending": "Mujer remendando",
    "Woman Reading": "Mujer leyendo",
    "Woman and Child at the Well": "Mujer y niño junto al pozo",
    "Woman at Her Toilette": "Mujer en su tocador",
    "Woman at the Piano": "Mujer al piano",
    "Woman before an Aquarium": "Mujer ante un acuario",
    "Woman in Front of a Still Life by Cezanne": "Mujer ante una naturaleza muerta de Cézanne",
    "Woman in a Garden": "Mujer en un jardín",
    "Woman on Rose Divan": "Mujer en un diván rosa",
    "Women Viewing Paintings": "Mujeres contemplando pinturas",
    # Y
    "Young Clergyman Reading": "Joven clérigo leyendo",
    "Young Man in a Turban": "Joven con turbante",
    "Young Peasant Having Her Coffee": "Joven campesina tomando su café",
    "Young Woman": "Mujer joven",
    "Young Woman Sewing": "Mujer joven cosiendo",
    "Young Woman at an Open Half-Door": "Mujer joven en una puerta entreabierta",
}


def main():
    d = json.load(open(PATH))
    paintings = d["paintings"]

    aplicadas = 0
    sin_traducir = []

    for p in paintings:
        original = p["titulo"]
        if original in TRADUCCIONES:
            p["titulo"] = TRADUCCIONES[original]
            aplicadas += 1
        else:
            sin_traducir.append(original)

    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)

    print(f"✅ Traducciones aplicadas: {aplicadas}/{len(paintings)}")
    print(f"   Sin traducir (ya en otro idioma o nombre propio): {len(sin_traducir)}")
    if sin_traducir:
        print("\nEjemplos sin traducir:")
        for t in sin_traducir[:15]:
            print(f"  {t!r}")

    print("\nEjemplos del resultado final:")
    for i in [0, 10, 50, 100, 200, 300]:
        p = paintings[i]
        print(f"  [{i}] {p['titulo']} — {p['artista']} ({p['anio']})")


if __name__ == "__main__":
    main()
